### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by alanhogan** [cmdrkeene/memegen#14]
On OS X Yosemite:

``` sh
~% sudo gem install memegen
# success
~% memegen --list
/Library/Ruby/Gems/2.0.0/gems/memegen-1.0.9/lib/meme_generator/cli.rb:2:in `images': uninitialized constant MemeGenerator (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/memegen-1.0.9/lib/meme_generator/cli.rb:11:in `list_generators'
    from /Library/Ruby/Gems/2.0.0/gems/memegen-1.0.9/bin/memegen:18:in `<top (required)>'
    from /usr/bin/memegen:23:in `load'
    from /usr/bin/memegen:23:in `<main>'
```

**Comment by amitailanciano** [comment]
@alanhogan I was having the same issue, I moved:

```
require "rubygems"
require "meme_generator"
```

in `/Library/Ruby/Gems/2.0.0/gems/memegen-1.0.9/bin/memegen`

to just above 

`require "meme_generator/cli"`

and it works now

**Comment by moribellamy** [comment]
I had the same issue, and @amitailanciano's fix works for me too.
