### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by PiotrMi** [cmdrkeene/memegen#15]
On Ubuntu 14.04

root@memegenerator:~# gem install memegen
Fetching: rmagick-2.15.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing memegen:
        ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from extconf.rb:4:in `<main>'

**Comment by Ginden** [comment]
This command worked for me:

```
sudo apt-get install libmagickwand-dev
```
Ubuntu 18.04.
